[package]
name = "cake-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bitcode = { version = "0.6.0", features = ["serde"] }

clap = { version = "4.5.8", features = ["derive"] }
human_bytes = "0.4.3"
lazy_static = "1.5.0"
log = "0.4.22"
memmap2 = "0.9.4"
memory-stats = "1.2.0"
regex = "1.10.5"
safetensors = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tokenizers = { version = "0.19.1", features = ["onig"] }
tokio = { version = "1.38.0", features = ["full"] }
yoke = { version = "0.7.4", features = ["derive"] }

# Metal acceleration on macOS
[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }
candle-nn = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }
candle-transformers = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }

[target.'cfg(target_os = "ios")'.dependencies]
candle-core = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }
candle-nn = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }
candle-transformers = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "metal",
] }

# CUDA on everything else.
[target.'cfg(not(any(target_os = "macos", target_os = "ios")))'.dependencies]
candle-core = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "cuda",
] }
candle-nn = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "cuda",
] }
candle-transformers = { git = "https://github.com/evilsocket/candle.git", branch = "metal_ios_support", features = [
    "cuda",
] }
