[package]
name = "llama3-cake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bitcode = { version = "0.6.0", features = ["serde"] }
candle-core = { version = "0.6.0", features = ["metal", "accelerate"] }
candle-nn = { version = "0.6.0", features = ["metal", "accelerate"] }
candle-transformers = { version = "0.6.0", features = ["metal", "accelerate"] }
clap = { version = "4.5.8", features = ["derive"] }
env_logger = "0.11.3"
human_bytes = "0.4.3"
log = "0.4.22"
memory-stats = "1.2.0"
safetensors = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokenizers = { version = "0.19.1", features = ["onig"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
